package com.vanniktech.emoji.googlecompat.category;

import android.support.annotation.DrawableRes;
import android.support.annotation.NonNull;
import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji;
import com.vanniktech.emoji.emoji.Emoji;
import com.vanniktech.emoji.emoji.EmojiCategory;
import com.vanniktech.emoji.googlecompat.R;

@SuppressWarnings("PMD.MethodReturnsInternalArray") public final class ObjectsCategory implements EmojiCategory {
  private static final Emoji[] DATA = new Emoji[] {
    new GoogleCompatEmoji(0x231a),
    new GoogleCompatEmoji(0x1f4f1),
    new GoogleCompatEmoji(0x1f4f2),
    new GoogleCompatEmoji(0x1f4bb),
    new GoogleCompatEmoji(new int[] { 0x2328, 0xfe0f }),
    new GoogleCompatEmoji(0x1f5a5),
    new GoogleCompatEmoji(0x1f5a8),
    new GoogleCompatEmoji(0x1f5b1),
    new GoogleCompatEmoji(0x1f5b2),
    new GoogleCompatEmoji(0x1f579),
    new GoogleCompatEmoji(0x1f5dc),
    new GoogleCompatEmoji(0x1f4bd),
    new GoogleCompatEmoji(0x1f4be),
    new GoogleCompatEmoji(0x1f4bf),
    new GoogleCompatEmoji(0x1f4c0),
    new GoogleCompatEmoji(0x1f4fc),
    new GoogleCompatEmoji(0x1f4f7),
    new GoogleCompatEmoji(0x1f4f8),
    new GoogleCompatEmoji(0x1f4f9),
    new GoogleCompatEmoji(0x1f3a5),
    new GoogleCompatEmoji(0x1f4fd),
    new GoogleCompatEmoji(0x1f39e),
    new GoogleCompatEmoji(0x1f4de),
    new GoogleCompatEmoji(0x260e),
    new GoogleCompatEmoji(0x1f4df),
    new GoogleCompatEmoji(0x1f4e0),
    new GoogleCompatEmoji(0x1f4fa),
    new GoogleCompatEmoji(0x1f4fb),
    new GoogleCompatEmoji(0x1f399),
    new GoogleCompatEmoji(0x1f39a),
    new GoogleCompatEmoji(0x1f39b),
    new GoogleCompatEmoji(new int[] { 0x23f1, 0xfe0f }),
    new GoogleCompatEmoji(new int[] { 0x23f2, 0xfe0f }),
    new GoogleCompatEmoji(0x23f0),
    new GoogleCompatEmoji(0x1f570),
    new GoogleCompatEmoji(0x231b),
    new GoogleCompatEmoji(0x23f3),
    new GoogleCompatEmoji(0x1f4e1),
    new GoogleCompatEmoji(0x1f50b),
    new GoogleCompatEmoji(0x1f50c),
    new GoogleCompatEmoji(0x1f4a1),
    new GoogleCompatEmoji(0x1f526),
    new GoogleCompatEmoji(0x1f56f),
    new GoogleCompatEmoji(0x1f5d1),
    new GoogleCompatEmoji(0x1f6e2),
    new GoogleCompatEmoji(0x1f4b8),
    new GoogleCompatEmoji(0x1f4b5),
    new GoogleCompatEmoji(0x1f4b4),
    new GoogleCompatEmoji(0x1f4b6),
    new GoogleCompatEmoji(0x1f4b7),
    new GoogleCompatEmoji(0x1f4b0),
    new GoogleCompatEmoji(0x1f4b3),
    new GoogleCompatEmoji(0x1f48e),
    new GoogleCompatEmoji(new int[] { 0x2696, 0xfe0f }),
    new GoogleCompatEmoji(0x1f527),
    new GoogleCompatEmoji(0x1f528),
    new GoogleCompatEmoji(new int[] { 0x2692, 0xfe0f }),
    new GoogleCompatEmoji(0x1f6e0),
    new GoogleCompatEmoji(new int[] { 0x26cf, 0xfe0f }),
    new GoogleCompatEmoji(0x1f529),
    new GoogleCompatEmoji(new int[] { 0x2699, 0xfe0f }),
    new GoogleCompatEmoji(new int[] { 0x26d3, 0xfe0f }),
    new GoogleCompatEmoji(0x1f52b),
    new GoogleCompatEmoji(0x1f4a3),
    new GoogleCompatEmoji(0x1f52a),
    new GoogleCompatEmoji(0x1f5e1),
    new GoogleCompatEmoji(new int[] { 0x2694, 0xfe0f }),
    new GoogleCompatEmoji(0x1f6e1),
    new GoogleCompatEmoji(0x1f6ac),
    new GoogleCompatEmoji(new int[] { 0x26b0, 0xfe0f }),
    new GoogleCompatEmoji(new int[] { 0x26b1, 0xfe0f }),
    new GoogleCompatEmoji(0x1f3fa),
    new GoogleCompatEmoji(0x1f52e),
    new GoogleCompatEmoji(0x1f4ff),
    new GoogleCompatEmoji(0x1f488),
    new GoogleCompatEmoji(new int[] { 0x2697, 0xfe0f }),
    new GoogleCompatEmoji(0x1f52d),
    new GoogleCompatEmoji(0x1f52c),
    new GoogleCompatEmoji(0x1f573),
    new GoogleCompatEmoji(0x1f48a),
    new GoogleCompatEmoji(0x1f489),
    new GoogleCompatEmoji(0x1f321),
    new GoogleCompatEmoji(0x1f6bd),
    new GoogleCompatEmoji(0x1f6b0),
    new GoogleCompatEmoji(0x1f6bf),
    new GoogleCompatEmoji(0x1f6c1),
    new GoogleCompatEmoji(0x1f6c0,
      new GoogleCompatEmoji(new int[] { 0x1f6c0, 0x1f3fb }),
      new GoogleCompatEmoji(new int[] { 0x1f6c0, 0x1f3fc }),
      new GoogleCompatEmoji(new int[] { 0x1f6c0, 0x1f3fd }),
      new GoogleCompatEmoji(new int[] { 0x1f6c0, 0x1f3fe }),
      new GoogleCompatEmoji(new int[] { 0x1f6c0, 0x1f3ff })
    ),
    new GoogleCompatEmoji(0x1f6ce),
    new GoogleCompatEmoji(0x1f511),
    new GoogleCompatEmoji(0x1f5dd),
    new GoogleCompatEmoji(0x1f6aa),
    new GoogleCompatEmoji(0x1f6cb),
    new GoogleCompatEmoji(0x1f6cf),
    new GoogleCompatEmoji(0x1f6cc,
      new GoogleCompatEmoji(new int[] { 0x1f6cc, 0x1f3fb }),
      new GoogleCompatEmoji(new int[] { 0x1f6cc, 0x1f3fc }),
      new GoogleCompatEmoji(new int[] { 0x1f6cc, 0x1f3fd }),
      new GoogleCompatEmoji(new int[] { 0x1f6cc, 0x1f3fe }),
      new GoogleCompatEmoji(new int[] { 0x1f6cc, 0x1f3ff })
    ),
    new GoogleCompatEmoji(0x1f5bc),
    new GoogleCompatEmoji(0x1f6cd),
    new GoogleCompatEmoji(0x1f6d2),
    new GoogleCompatEmoji(0x1f381),
    new GoogleCompatEmoji(0x1f388),
    new GoogleCompatEmoji(0x1f38f),
    new GoogleCompatEmoji(0x1f380),
    new GoogleCompatEmoji(0x1f38a),
    new GoogleCompatEmoji(0x1f389),
    new GoogleCompatEmoji(0x1f38e),
    new GoogleCompatEmoji(0x1f3ee),
    new GoogleCompatEmoji(0x1f390),
    new GoogleCompatEmoji(new int[] { 0x2709, 0xfe0f }),
    new GoogleCompatEmoji(0x1f4e9),
    new GoogleCompatEmoji(0x1f4e8),
    new GoogleCompatEmoji(0x1f4e7),
    new GoogleCompatEmoji(0x1f48c),
    new GoogleCompatEmoji(0x1f4e5),
    new GoogleCompatEmoji(0x1f4e4),
    new GoogleCompatEmoji(0x1f4e6),
    new GoogleCompatEmoji(0x1f3f7),
    new GoogleCompatEmoji(0x1f4ea),
    new GoogleCompatEmoji(0x1f4eb),
    new GoogleCompatEmoji(0x1f4ec),
    new GoogleCompatEmoji(0x1f4ed),
    new GoogleCompatEmoji(0x1f4ee),
    new GoogleCompatEmoji(0x1f4ef),
    new GoogleCompatEmoji(0x1f4dc),
    new GoogleCompatEmoji(0x1f4c3),
    new GoogleCompatEmoji(0x1f4c4),
    new GoogleCompatEmoji(0x1f4d1),
    new GoogleCompatEmoji(0x1f4ca),
    new GoogleCompatEmoji(0x1f4c8),
    new GoogleCompatEmoji(0x1f4c9),
    new GoogleCompatEmoji(0x1f5d2),
    new GoogleCompatEmoji(0x1f5d3),
    new GoogleCompatEmoji(0x1f4c6),
    new GoogleCompatEmoji(0x1f4c5),
    new GoogleCompatEmoji(0x1f4c7),
    new GoogleCompatEmoji(0x1f5c3),
    new GoogleCompatEmoji(0x1f5f3),
    new GoogleCompatEmoji(0x1f5c4),
    new GoogleCompatEmoji(0x1f4cb),
    new GoogleCompatEmoji(0x1f4c1),
    new GoogleCompatEmoji(0x1f4c2),
    new GoogleCompatEmoji(0x1f5c2),
    new GoogleCompatEmoji(0x1f5de),
    new GoogleCompatEmoji(0x1f4f0),
    new GoogleCompatEmoji(0x1f4d3),
    new GoogleCompatEmoji(0x1f4d4),
    new GoogleCompatEmoji(0x1f4d2),
    new GoogleCompatEmoji(0x1f4d5),
    new GoogleCompatEmoji(0x1f4d7),
    new GoogleCompatEmoji(0x1f4d8),
    new GoogleCompatEmoji(0x1f4d9),
    new GoogleCompatEmoji(0x1f4da),
    new GoogleCompatEmoji(0x1f4d6),
    new GoogleCompatEmoji(0x1f516),
    new GoogleCompatEmoji(0x1f517),
    new GoogleCompatEmoji(0x1f4ce),
    new GoogleCompatEmoji(0x1f587),
    new GoogleCompatEmoji(0x1f4d0),
    new GoogleCompatEmoji(0x1f4cf),
    new GoogleCompatEmoji(0x1f4cc),
    new GoogleCompatEmoji(0x1f4cd),
    new GoogleCompatEmoji(new int[] { 0x2702, 0xfe0f }),
    new GoogleCompatEmoji(0x1f58a),
    new GoogleCompatEmoji(0x1f58b),
    new GoogleCompatEmoji(new int[] { 0x2712, 0xfe0f }),
    new GoogleCompatEmoji(0x1f58c),
    new GoogleCompatEmoji(0x1f58d),
    new GoogleCompatEmoji(0x1f4dd),
    new GoogleCompatEmoji(new int[] { 0x270f, 0xfe0f }),
    new GoogleCompatEmoji(0x1f50d),
    new GoogleCompatEmoji(0x1f50e),
    new GoogleCompatEmoji(0x1f50f),
    new GoogleCompatEmoji(0x1f510),
    new GoogleCompatEmoji(0x1f512),
    new GoogleCompatEmoji(0x1f513),
  };

  @Override @NonNull public Emoji[] getEmojis() {
    return DATA;
  }

  @Override @DrawableRes public int getIcon() {
    return R.drawable.emoji_compat_category_objects;
  }
}
