package com.vanniktech.emoji.googlecompat.category;

import android.support.annotation.DrawableRes;
import android.support.annotation.NonNull;
import com.vanniktech.emoji.googlecompat.GoogleCompatEmoji;
import com.vanniktech.emoji.emoji.Emoji;
import com.vanniktech.emoji.emoji.EmojiCategory;
import com.vanniktech.emoji.googlecompat.R;

@SuppressWarnings("PMD.MethodReturnsInternalArray") public final class TravelCategory implements EmojiCategory {
  private static final Emoji[] DATA = new Emoji[] {
    new GoogleCompatEmoji(0x1f697),
    new GoogleCompatEmoji(0x1f695),
    new GoogleCompatEmoji(0x1f699),
    new GoogleCompatEmoji(0x1f68c),
    new GoogleCompatEmoji(0x1f68e),
    new GoogleCompatEmoji(0x1f3ce),
    new GoogleCompatEmoji(0x1f693),
    new GoogleCompatEmoji(0x1f691),
    new GoogleCompatEmoji(0x1f692),
    new GoogleCompatEmoji(0x1f690),
    new GoogleCompatEmoji(0x1f69a),
    new GoogleCompatEmoji(0x1f69b),
    new GoogleCompatEmoji(0x1f69c),
    new GoogleCompatEmoji(0x1f6f4),
    new GoogleCompatEmoji(0x1f6b2),
    new GoogleCompatEmoji(0x1f6f5),
    new GoogleCompatEmoji(0x1f3cd),
    new GoogleCompatEmoji(0x1f6a8),
    new GoogleCompatEmoji(0x1f694),
    new GoogleCompatEmoji(0x1f68d),
    new GoogleCompatEmoji(0x1f698),
    new GoogleCompatEmoji(0x1f696),
    new GoogleCompatEmoji(0x1f6a1),
    new GoogleCompatEmoji(0x1f6a0),
    new GoogleCompatEmoji(0x1f69f),
    new GoogleCompatEmoji(0x1f683),
    new GoogleCompatEmoji(0x1f68b),
    new GoogleCompatEmoji(0x1f69e),
    new GoogleCompatEmoji(0x1f69d),
    new GoogleCompatEmoji(0x1f684),
    new GoogleCompatEmoji(0x1f685),
    new GoogleCompatEmoji(0x1f688),
    new GoogleCompatEmoji(0x1f682),
    new GoogleCompatEmoji(0x1f686),
    new GoogleCompatEmoji(0x1f687),
    new GoogleCompatEmoji(0x1f68a),
    new GoogleCompatEmoji(0x1f689),
    new GoogleCompatEmoji(0x1f681),
    new GoogleCompatEmoji(0x1f6e9),
    new GoogleCompatEmoji(new int[] { 0x2708, 0xfe0f }),
    new GoogleCompatEmoji(0x1f6eb),
    new GoogleCompatEmoji(0x1f6ec),
    new GoogleCompatEmoji(0x1f680),
    new GoogleCompatEmoji(0x1f6f0),
    new GoogleCompatEmoji(0x1f4ba),
    new GoogleCompatEmoji(0x1f6f6),
    new GoogleCompatEmoji(0x26f5),
    new GoogleCompatEmoji(0x1f6e5),
    new GoogleCompatEmoji(0x1f6a4),
    new GoogleCompatEmoji(0x1f6f3),
    new GoogleCompatEmoji(new int[] { 0x26f4, 0xfe0f }),
    new GoogleCompatEmoji(0x1f6a2),
    new GoogleCompatEmoji(0x2693),
    new GoogleCompatEmoji(0x1f6a7),
    new GoogleCompatEmoji(0x26fd),
    new GoogleCompatEmoji(0x1f68f),
    new GoogleCompatEmoji(0x1f6a6),
    new GoogleCompatEmoji(0x1f6a5),
    new GoogleCompatEmoji(0x1f5fa),
    new GoogleCompatEmoji(0x1f5ff),
    new GoogleCompatEmoji(0x1f5fd),
    new GoogleCompatEmoji(new int[] { 0x26f2, 0xfe0f }),
    new GoogleCompatEmoji(0x1f5fc),
    new GoogleCompatEmoji(0x1f3f0),
    new GoogleCompatEmoji(0x1f3ef),
    new GoogleCompatEmoji(0x1f3df),
    new GoogleCompatEmoji(0x1f3a1),
    new GoogleCompatEmoji(0x1f3a2),
    new GoogleCompatEmoji(0x1f3a0),
    new GoogleCompatEmoji(new int[] { 0x26f1, 0xfe0f }),
    new GoogleCompatEmoji(0x1f3d6),
    new GoogleCompatEmoji(0x1f3dd),
    new GoogleCompatEmoji(new int[] { 0x26f0, 0xfe0f }),
    new GoogleCompatEmoji(0x1f3d4),
    new GoogleCompatEmoji(0x1f5fb),
    new GoogleCompatEmoji(0x1f30b),
    new GoogleCompatEmoji(0x1f3dc),
    new GoogleCompatEmoji(0x1f3d5),
    new GoogleCompatEmoji(0x26fa),
    new GoogleCompatEmoji(0x1f6e4),
    new GoogleCompatEmoji(0x1f6e3),
    new GoogleCompatEmoji(0x1f3d7),
    new GoogleCompatEmoji(0x1f3ed),
    new GoogleCompatEmoji(0x1f3e0),
    new GoogleCompatEmoji(0x1f3e1),
    new GoogleCompatEmoji(0x1f3d8),
    new GoogleCompatEmoji(0x1f3da),
    new GoogleCompatEmoji(0x1f3e2),
    new GoogleCompatEmoji(0x1f3ec),
    new GoogleCompatEmoji(0x1f3e3),
    new GoogleCompatEmoji(0x1f3e4),
    new GoogleCompatEmoji(0x1f3e5),
    new GoogleCompatEmoji(0x1f3e6),
    new GoogleCompatEmoji(0x1f3e8),
    new GoogleCompatEmoji(0x1f3ea),
    new GoogleCompatEmoji(0x1f3eb),
    new GoogleCompatEmoji(0x1f3e9),
    new GoogleCompatEmoji(0x1f492),
    new GoogleCompatEmoji(0x1f3db),
    new GoogleCompatEmoji(0x26ea),
    new GoogleCompatEmoji(0x1f54c),
    new GoogleCompatEmoji(0x1f54d),
    new GoogleCompatEmoji(0x1f54b),
    new GoogleCompatEmoji(new int[] { 0x26e9, 0xfe0f }),
    new GoogleCompatEmoji(0x1f5fe),
    new GoogleCompatEmoji(0x1f391),
    new GoogleCompatEmoji(0x1f3de),
    new GoogleCompatEmoji(0x1f305),
    new GoogleCompatEmoji(0x1f304),
    new GoogleCompatEmoji(0x1f320),
    new GoogleCompatEmoji(0x1f387),
    new GoogleCompatEmoji(0x1f386),
    new GoogleCompatEmoji(0x1f307),
    new GoogleCompatEmoji(0x1f306),
    new GoogleCompatEmoji(0x1f3d9),
    new GoogleCompatEmoji(0x1f303),
    new GoogleCompatEmoji(0x1f30c),
    new GoogleCompatEmoji(0x1f309),
    new GoogleCompatEmoji(0x1f301),
  };

  @Override @NonNull public Emoji[] getEmojis() {
    return DATA;
  }

  @Override @DrawableRes public int getIcon() {
    return R.drawable.emoji_compat_category_travel;
  }
}
